=== wiliamoliveira/mestrado.rebeca/src/main/resources/configuration.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="1.0">
	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="r" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="sigma" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="sigmaE" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="miE" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="convYield" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="velRev" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="T" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="c1" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="c2" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="tau" type="xs:double" minOccurs="1" maxOccurs="1" />
				<!-- <xs:element name="q" type="xs:double" minOccurs="1" maxOccurs="1" /> -->
				<xs:element name="accuracy" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="P0" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="Pmax" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="E0" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="Emin" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="Ebarra" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="qMax" type="xs:double" minOccurs="1" maxOccurs="1" />
				<xs:element name="timeInMonth" type="xs:boolean" minOccurs="1" maxOccurs="1" />
				<xs:element name="growthRate" type="xs:double" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== wiliamoliveira/mestrado.rebeca/src/main/resources/configuration.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="configuration.xsd">
	<r>0.05</r>
	<sigma>0.19</sigma>
	<sigmaE>0.1</sigmaE>
	<miE>0.04</miE>
	<convYield>0.046</convYield>
	<velRev>4.0E-4</velRev>
	<T>10.0</T>
	<c1>20.0</c1>
	<c2>30.0</c2>
	<tau>0.33</tau>
	<accuracy>5</accuracy>
	<P0>75.0</P0>
	<Pmax>200.0</Pmax>
	<E0>80.0</E0>
	<Emin>30.0</Emin>
	<Ebarra>600.0</Ebarra>
	<qMax>0.0</qMax>
	<timeInMonth>true</timeInMonth>
	<growthRate>0.017</growthRate>
</config>
